mindmap
Responsable de formation

      ce qu'il dit

        Il y a deux filières : développement web et développement mobile.

        Chaque filière est composée de plusieurs modules avec une masse horaire définie .

        Chaque module comprend des compétences.

        Chaque compétence à différents niveaux imité , adapté , transposé.
      
      ce qu'il fait

        Pour chaque filière, découvrez les modules avec leurs compétences ainsi que la masse horaire de chaque module.

        De plus, retrouvez la définition de chaque compétence et de chaque niveau dans ces compétences.