mindmap
Formateur
  
       ce qu'il fait
        Evaluer les projets des apprenants

        Fournir des commentaires détaillés pour aider les apprenants à progresser 



      ce qu'il dit

       Il doit effectuer la validation du projet et des briefs