---
title: Diagramme d'état de projet
---
stateDiagram-v2

    state "En rédaction" as en_redaction
    state "En cours" as en_cours
    state "En pause" as en_pause
    state "En validation" as en_validation
    state "Terminé" as termine

    [*] --> en_redaction
    en_redaction --> en_cours
    en_cours --> termine
    en_cours --> en_pause
    en_cours --> en_validation
    en_validation --> en_cours
    en_validation --> termine
    en_validation --> en_pause
    en_pause --> en_cours
    termine --> [*]