@startuml uses_cases_pkg_validations

left to right direction
actor Formateur



package pkg_validations {

 
  (Valider un Projet) <.. (Définir les Appreciation de Validation pour chaque compétence):<<Extend>>
  (Valider un Projet) <.. (Saisie des Messages pour chaque compétence):<<Extend>>
} 


package pkg_realisation_projet{

   Formateur -- (Consulter la liste des projets réalisés en attente de validation)
   (Consulter la liste des projets réalisés en attente de validation) <.. (Valider un Projet):<<Extend>>

}

@enduml