@startuml uses_cases_pkg_validations

left to right direction
actor Formateur
actor Apprenant


package pkg_validations {
 (Évaluer un Projet)  #palegreen
  Formateur -- (Évaluer un Projet)
  Formateur -- (Définir les Niveaux de Validation pour chaque compétence)
  Formateur -- (Consulter le Tableau de Bord)/
  Formateur -- (Recevoir des Notifications)/

  Apprenant -- (Soumettre un Projet)
  Apprenant -- (Consulter les Évaluations)/
  Apprenant -- (Recevoir des Notifications)/

  (Évaluer un Projet) <.. (Définir les Niveaux de Validation pour chaque compétence)
  (Évaluer un Projet) <.. (Ajouter des Commentaires)
  (Consulter les Évaluations) <.. (Voir les statistiques d''Évaluation)
  (Évaluer un Projet)<.. (Voir liste des Projets en Attente de validation)

}  

@enduml