%% @config(../mindmap-config.json)
mindmap
Formateur

      ce qu'il fait
        Suivi des autoformations sur la table Excel
        Suivi de l'avancement des apprenants et des compétences sur la table Excel ou sur papier
      ce qu'il dit
        Il y a une difficulté pour suivre chaque apprenant et voir les statistiques.
        Il y a une difficulté pour suivre l'avancement des apprenants sur les briefs et les projets.