%% @config(../mindmap-config.json)
mindmap
Formateur

    Ce qu'il fait
      Suivi de l'avancement des apprenants et des compétences sur la table Excel ou sur papier
      Utilise des outils manuels pour suivre les progrès et les réalisations des apprenants.
    Ce qu'il dit
      Il y a une difficulté pour suivre l'avancement des apprenants sur les briefs et les projets.
      C'est difficile pour moi de voir quelles compétences sont validées par chaque apprenant sur chaque projet.