%% @config(../mindmap-config.json)
mindmap
Apprenant

       ce qu'il fait
        Suit son avancement en autoformation sur la table Excel ou directement sur la plateforme de cours.
        Consulte ses compétences sur la table Excel.

      ce qu'il dit
        Il y a une difficulté pour suivre mon avancement sur l'autoformation.
        Il y a une difficulté pour suivre mon avancement sur les projets par rapport à mes collègues en classe et pour consulter mes compétences validées.