%% @config(../mindmap-config.json)
mindmap
Apprenant

       ce qu'il fait
        Suit son avancement en autoformation sur un tableur Excel ou directement sur la plateforme de cours
        Consulte ses compétences sur un tableur Excel

      ce qu'il dit
        Il y a une difficulté pour suivre mon avancement en autoformation.
        Il y a une difficulté pour suivre mon avancement sur la réalisation des projets par rapport à mes collègues de classe