@startuml uses_cases_pkg_suivi

actor Formateur
actor Apprenant

package pkg_suivi {

  Formateur --> (suivi l'avencement des projets)
  Formateur --> (suivi l'avencement des compétences)

  Apprenant --> (suivi l'avencement des projets)
  Apprenant --> (suivi l'avencement des compétences)
  
  (suivi l'avencement des projets) <.. (consulter la table d'avencement des projet)
  (suivi l'avencement des projets) <.. (filtrer par projets)
  (suivi l'avencement des compétences) <.. (consulter la table de validation des compétences)
  (suivi l'avencement des compétences) <.. (filtrer les compétences par apprenant)
  

}  

@enduml