@startuml uses_cases_pkg_rh

left to right direction


package pkg_rh {

  Responsable_de_Formation ----> (gestion des specialites)
  Responsable_de_Formation ----> (gestion des groupes) 
  Responsable_de_Formation ----> (gestion des villes) 
  Responsable_de_Formation ----> (gestion des apprenant) 
  Responsable_de_Formation ----> (gestion des formateurs) 

  ' (gestion des formateurs) <... (Auth) : <<extend>>
  ' (gestion des apprenant) <... (Auth) : <<extend>>
  ' (gestion des groupes) <... (Auth) : <<extend>>
  ' (gestion des villes) <... (Auth) : <<extend>>
  ' (gestion des specialites) <... (Auth) : <<extend>>

}  

@enduml