@startuml uses_cases_pkg_rh

left to right direction


package pkg_rh {

  Responsable_de_Formation ----> (gestion des specialites)
  Responsable_de_Formation ----> (gestion des niveaux scolaire)
  Responsable_de_Formation ----> (gestion des groupes) 
  Responsable_de_Formation ----> (gestion des villes) 
  Responsable_de_Formation ----> (gestion des apprenant) 
  Responsable_de_Formation ----> (gestion des formateurs) 

  (gestion des formateurs) <... (Authentification) : <<extend>>
  (gestion des apprenant) <... (Authentification) : <<extend>>
  (gestion des groupes) <... (Authentification) : <<extend>>
  (gestion des villes) <... (Authentification) : <<extend>>
  (gestion des niveaux scolaire) <... (Authentification) : <<extend>>
  (gestion des specialites) <... (Authentification) : <<extend>>

}  

@enduml