@startuml uses_cases_pkg_realisation_projets

left to right direction


actor Apprenant as apprenant
actor Formateur as formateur
package pkg_realisation_projets {


  apprenant --> (Soumet le livrable pour validation)
  apprenant --> (Consulte l'état de son projet)
  formateur --> (Consulte la liste des projets réalisés)
  (Consulte l'état de progression et validation des projets) <.. (Consulte la liste des projets réalisés) : <<extend>>
  (Soumet le livrable pour validation) <.. (Change l'état des projets en progression) : <<extend>>
}

@enduml
