classDiagram

direction LR


namespace pkg_competences {
class Competence 
  %% Description d'un niveau de compétence
class NiveauCompetence 
class Technologie 
class CategorieTechnologie 
}
Competence "1" -- "*" NiveauCompetence



Competence "1" --> "*" Technologie 
Technologie "*" --> "1" CategorieTechnologie




namespace pkg_rh {
  class Utilisateur 
  class Personne
  class Formateur 
  class Apprenant
  class  Groupe 
  class  Ville
  class  NivaeuScholaire
  class Specialite
}
Personne <|-- Formateur
Personne <|-- Apprenant 
Utilisateur "1" <-- "1" Formateur : "compte"
Utilisateur "1" <-- "1" Apprenant : "compte"
Apprenant  "*" --> "1"  Groupe 
Formateur "*" --> "1" Groupe
Formateur "*" --> "1" Specialite
Apprenant "*" --> "1" NivaeuScholaire

namespace pkg_creation_projets {
  class BriefProjet 
  class Tache 
  class Resource 
  class Livrable 
  class TransfertCompetence
  class EtatRealisation 
  class StatutTache 

}
BriefProjet "*" <-- "1" Formateur :"*"
BriefProjet "1" --> "*" Resource
BriefProjet "1" --> "*" Livrable
BriefProjet "1" --> "*" EtatRealisation
BriefProjet "1" -- "*" TransfertCompetence
TransfertCompetence "*" -- "1" Competence : "*"
TransfertCompetence "*" -- "1" Appreciation


BriefProjet "1" --> "*" Tache
Tache "*" --> "1" Apprenant : 1
Tache "*" --> "1" NiveauCompetence
Tache "*" --> "*" Technologie
Tache "*" --> "1" StatutTache 
Equipe "*" --> "1" BriefProjet
Equipe   "*" --> "*"  Apprenant  : *



namespace pkg_realisation_projets {
class Realisation 
class LivrableRealisation 
}
Realisation "*" --> "1" EtatRealisation
Realisation "1" --> "*" LivrableRealisation
Realisation "*" --> "1" BriefProjet

namespace pkg_validations {
class Validation 
class Appreciation
}
Validation "*" --> "1" Appreciation
Validation "*" --> "1" TransfertCompetence
Validation  "*" --> "1" Realisation
Appreciation "*" --> "1" NiveauCompetence

namespace pkg_formations {
  class Formation
}



