%% @config(../mindmap-config.json)
mindmap
Formateur

       ce qu'il fait
        Crée et gère des liens de formation, les activités, Utilisation des ressources disponibles.
        Offrir une formation adaptée à chaque apprenant pour favoriser leur réussite et leur développement..

        

      ce qu'il dit

        La création du plan de formation peut parfois être difficile, car il faut trouver le bon équilibre entre ce que nous voulons enseigner, ce que nous avons à notre disposition et le temps dont nous disposons.    