@startuml uses_cases_pkg_formations

left to right direction

actor Formateur
actor Apprennant 

package pkg_formations {

  Formateur -- (Gestions des formations)
  Apprennant -- (Consultations des formations)
  
  (Gestions des formations) ..> (Authentification) : include
  (Consultations des formations) ..> (Authentification) : include
}

@enduml
