%% @config(../../../modélisation/mindmap-config.json)
mindmap
Apprenant

       ce qu'il fait
        Travaille sur le projet régulièrement
        Soumet le livrable pour validation
        Cherche des ressources supplémentaires pour améliorer le projet

      ce qu'il dit

        J'ai besoin  Change l'état des projets en progression
      J'ai besoin   Consulte l'état de son projet
      Il est difficile de consulter mes compétences validées de manière claire et organisée.
      

       
