%% @config(../mindmap-config.json)
mindmap
Apprenant

      Ce qu'il fait
        Consulte ses compétences sur la table Excel.

      Ce qu'il dit
        Il y a une difficulté pour suivre mon avancement sur les projets par rapport à mes collègues en classe.
        Il est difficile de consulter mes compétences validées de manière claire et organisée.
        J'aimerais avoir un outil qui me permette de voir facilement mes progrès et mes compétences validées.