gantt
    title Soli-LMS Project Timeline
    dateFormat  YYYY-MM-DD
    excludes    weekends

    section PFR Sprint 1
    Lancement du Projet :done, 2024-05-22, 1d
    Créer un backlog initial avec des épics et des user stories :done, 2024-05-22, 1d
    Configuration du Tableau Jira :done, 2024-05-23, 1d
    Creation du Backlog Initial :done, 2024-05-23, 1d
    Besoin :done, 2024-05-19, 4d
    Créer des cartes d'empathie pour comprendre les besoins des utilisateurs :done, 2024-05-19, 1d
    Entretiens d'Empathie :done, 2024-05-19, 3d
    Cartes d'Empathie :done, 2024-05-23, 1d
    Definir le probleme :done, 2024-05-23, 1d
    Ideation :done, 2024-05-23, 1d
    Analyse du Projet :done, 2024-05-23, 1d
    Identifier et lister les outils et technologies nécessaires :done, 2024-05-23, 1d
    Identification des Outils et Technologies :done, 2024-05-23, 1d
    Identification de l'architecture de l'application :done, 2024-05-23, 1d
    Conception :done, 2024-05-24, 1d
    Créer des diagrammes UML :done, 2024-05-24, 1d
    Création du Diagramme de Cas d'Utilisation :done, 2024-05-24, 1d
    Création du Diagramme de Classes :done, 2024-05-24, 1d
    Conception du Diagramme de Sequence :done, 2024-05-24, 1d
    Maquettage :done, 2024-05-25, 3d
    Mettre en place les interfaces frontales :done, 2024-05-25, 3d
    Maquettes Cote Formateur :done, 2024-05-25, 1d
    Maquettes Cote Apprenant :done, 2024-05-27, 1d
    Realisation :2024-05-29, 6d
    Test :2024-06-05, 7d
    Deploiement :2024-06-12, 6d


