%% @config(../mindmap-config.json)
mindmap
Formateur

       ce qu'il fait
        Il évalue les projets des apprenants

        Il fournit des commentaires détaillés pour les aider à progresser 



      ce qu'il dit

       Il doit effectuer la validation du projet et des briefs