mindmap
Responsable de formation

      ce qu'il dit

        Nous avons eu un peu de mal à gérer les étudiants et formateurs dans Excel

        Il est difficile de valider les compétences des étudiants dans Excel
      
      ce qu'il fait
        Ajouter des étudiants et des formateurs
