%% @config(../mindmap-config.json)
mindmap
    Formateur
        Ce qu'il dit
            Accès pour voir les compétences
            Permet de choisir brief qui peut être utilisée pour noter les compétences
            
        Ce qu'il fait
            Donner une note pour chaque compétence. Chaque compétence a 3 niveaux et chaque niveau est limité entre la note minimale et la note maximale