@startuml 

left to right direction


actor Formateur as formateur
actor responsable de formation as responsable de formation

package pkg_competences {

  formateur -->  (Gestion des compétences) 
  formateur -->  (Gestion des niveaux de compétences) 
  formateur -->  (Gestion des technologies) 
  formateur -->  (Gestion des catégories des technologies)

  responsable de formation -->  (Gestion des compétences)


  (Gestion des technologies) <..  (Ajouter) : <<extend>>
  (Ajouter) <. (Affecter la technologie à une compétence)   : <<extend>>
   (Ajouter) <. (Affecter la technologie à une catégorie)   : <<extend>>
}  

' note right of admin : "note 1"

@enduml