gantt
    dateFormat  YYYY-MM-DD
    title Diagramme de gantt
    section Besoin
        Cart d'empathie  :done, 2024-03-29, 2024-04-05
        Définir de problème :done, 2024-04-05, 2024-05-07
    section Analyse
        Idéation :done, 2024-04-05, 2024-05-10
        Diagamme de cas d’utilisation :done, 2024-05-05, 2024-05-15
    section Analyse technique
        Capture des bosoin technique :done, 2024-05-12, 2024-05-15
    section Conception generique
        Diagramme de class :done,  2024-03-15, 2024-04-20
        Prototype :done,  2024-04-20, 2024-05-20
    section Conception
        Diagramme de class :done,  2024-04-15, 2024-05-10
        Maquette :done,  2024-05-10, 2024-05-22
    section Base de donnes
        Base de donnes :done,  2024-05-13, 2024-06-01
    section Backend
        Backend pkg_realisation_projets :done,  2024-06-01, 2024-06-05
    section Front end
        Front end pkg_realisation_projets :done,  2024-06-02, 2024-06-06
    section Test
        Test pkg_realisation_projets :done,  2024-06-02, 2024-06-06
    section Tests et déploiement
        Déploiement :done,  2024-06-06, 2024-06-10