%% @config(../mindmap-config.json)
mindmap
Formateur

       ce qu'il fait
        Crée et gère des projets de formation en définissant les objectifs, les activités, les ressources et les évaluations.
        Surveille et ajuste les projets en fonction des besoins et des retours des étudiants.


      ce qu'il dit

        La création du brief peut être un défi car il faut équilibrer les objectifs pédagogiques avec les ressources disponibles et le temps imparti .
        Nous devons constamment rappeler aux apprenants quelles compétences sont visées dans chaque projet, car ils ont du mal à les retenir.

