%% @config(../../../modélisation/mindmap-config.json)
mindmap
  root((Formateur))
    Ce qu'il fait
        Gère projets avec outils multiples
        Evalue projets individuellement
    Ce qu'il dit
        Suivi apprenants difficile
        Manque de vision sur les difficultés
        Besoin d'un système plus efficace