%% @config(../../../modélisation/mindmap-config.json)
mindmap
  root((Formateur))
     Ce qu'il dit
      Il rencontre des défis pour le suivi de l'avancement des compétences des apprenants.
      Ils ne savent pas s'il y a des apprenants rencontrant des défis dans leur réalisation de projets.
      Ils devraient  fournir une appréciation spécifique et personnalisée pour la validation des brief et des projets. 
    Ce qu'il fait
      Nous utilisons Trello et Excel pour la gestion des tâches.
    Nous travaillons avec GitHub et Google Drive pour l'affectation des projets et des briefs.

   