%% @config(../../../modélisation/mindmap-config.json)
mindmap
  root((Apprenant))
    ce qu'il faisait avant
       Affectation projets via Excel
       Difficulté suivi projet 
       Ressources dispersées
    ce qu'il dit
       Que dois-je faire ?
       Comment suivre mon avancement ?
       Trouver les ressources prend du temps.
       
