%% @config(../../../modélisation/mindmap-config.json)
mindmap
Formateur

       ce qu'il fait
        Consulte la liste des projets réalisés.
      ce qu'il dit

       J'ai besoin de voir tous les projets avec leurs états de progressions et validations


       
